services:
  uptime-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-tracker
    ports:
      - "5000:5000"
    volumes:
      # Mount config directory for easy configuration updates
      - ./backend/external:/uptime-tracker/backend/external
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/services"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s